[/Script/EngineSettings.GameMapsSettings]
EditorStartupMap=/Game/Maps/L_Main
GameDefaultMap=/Game/Maps/L_Main
GlobalDefaultGameMode=/Script/Engine.GameModeBase

; Optional sandbox cache profile: -ddc=BeastLocalDDC
[BeastLocalDDC]
Root=(Type=Hierarchical,Inner=EnginePak,Inner=Local)
EnginePak=(Type=ReadPak,Filename="%ENGINEDIR%DerivedDataCache/Compressed.ddp",Compressed=true)
Local=(Type=FileSystem,Path="%GAMEDIR%DerivedDataCache",DeleteUnused=false)
